name: Upload Workflow

on:
  workflow_dispatch:  # Permite o acionamento manual via API
  push:
    branches:
      - main  # Substitua com a sua branch principal se necessário

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Upload File to GitHub Pages
        run: |
          # Adicione os comandos de upload de arquivos ou execução do processo desejado
          echo "Processo de upload ou outra ação desejada"
